export const PROTOCOL_VERSION = 1;
export const MAXIMUM_PAYLOAD_SIZE = 512;
export const SYNC_1 = 0xb5;
export const SYNC_2 = 0x62;

export const MessageId = Object.freeze({
  HEARTBEAT: 0x0001,
  ACK: 0x0002,
  GET_SETTINGS: 0x0100,
  SETTINGS: 0x0101,
  SET_CONTROLLER: 0x0110,
  SET_DRIVER_DIAGNOSTIC: 0x0111,
  SET_CURRENT_SENSE: 0x0112,
  SET_PARAMETER: 0x0113,
  SAVE_CONTROLLER: 0x0114,
  SELECT_PROFILE: 0x0120,
  GET_PROFILES: 0x0121,
  PROFILE_CONFIGURATION: 0x0122,
  SET_PROFILE: 0x0123,
  CREATE_PROFILE: 0x0124,
  SET_DEFAULT_PROFILE: 0x0125,
  GET_LOAD_CONFIGURATION: 0x0130,
  LOAD_CONFIGURATION: 0x0131,
  SET_LOAD_CONFIGURATION: 0x0132,
  GET_BEARING_CONFIGURATION: 0x0133,
  BEARING_CONFIGURATION: 0x0134,
  SET_BEARING_CONFIGURATION: 0x0135,
  START_RUN: 0x0200,
  STOP_RUN: 0x0201,
  MOTOR_TEST: 0x0202,
  CLEAR_FAULTS: 0x0203,
  ARM: 0x0204,
  START_VELOCITY_TEST: 0x0205,
  START_VELOCITY_SEQUENCE: 0x0206,
  START_STREAM: 0x0210,
  STOP_STREAM: 0x0211,
  TELEMETRY: 0x0220,
  CURRENT_CALIBRATION: 0x0300,
  SUPPLY_VOLTAGE_CALIBRATION: 0x0301,
  CURRENT_CALIBRATION_STATUS: 0x0302,
  ROTOR_ZERO_CALIBRATION: 0x0303,
  ROTOR_ZERO_CALIBRATION_STATUS: 0x0304,
  ZERO_INDEX_HYSTERESIS_CALIBRATION: 0x0305,
  ZERO_INDEX_HYSTERESIS_CALIBRATION_STATUS: 0x0306,
  CHARACTERIZATION_RESULT: 0x0310,
  CHARACTERIZATION_ACTION: 0x0311,
  CHARACTERIZATION_STATUS: 0x0312
});

export const MessageName = Object.freeze(Object.fromEntries(
  Object.entries(MessageId).map(([name, id]) => [id, name])
));

export const ResultCode = Object.freeze({
  OK: 0,
  INVALID_MESSAGE: 1,
  INVALID_LENGTH: 2,
  INVALID_VALUE: 3,
  UNSAFE_STATE: 4,
  STORAGE_FAILURE: 5
});

export const ResultName = Object.freeze(Object.fromEntries(
  Object.entries(ResultCode).map(([name, value]) => [value, name])
));

export const RunState = Object.freeze({
  DISARMED: 0,
  ARMED: 1,
  RUNNING: 2,
  FAULT: 3
});

export const FaultFlag = Object.freeze({
  NONE: 0x00000000,
  CONTROL_OVERRUN: 0x00000001,
  DRIVER_DIAGNOSTIC: 0x00000002,
  OVER_CURRENT: 0x00000004,
  ENCODER_TIMEOUT: 0x00000008,
  INVALID_CONFIGURATION: 0x00000010,
  UNDER_VOLTAGE: 0x00000020,
  OVER_VOLTAGE: 0x00000040
});

export const StopMode = Object.freeze({
  COAST: 0,
  BRAKE_TO_GROUND: 1,
  BRAKE_TO_SUPPLY: 2
});

export const ProfileKind = Object.freeze({
  RAMP: 0,
  SINE: 1,
  WAYPOINTS: 2
});

export const CurrentCalibrationAction = Object.freeze({
  RESET: 0,
  CAPTURE_POINT_1: 1,
  CAPTURE_POINT_2: 2,
  SAVE: 3,
  CANCEL: 4,
  REQUEST_STATUS: 5
});

export const RotorZeroCalibrationAction = Object.freeze({
  CAPTURE: 0,
  SAVE: 1,
  CANCEL: 2,
  REQUEST_STATUS: 3
});

export const ZeroIndexCalibrationAction = Object.freeze({
  START: 0,
  SELECT_REFERENCE_SIDE: 1,
  SAVE: 2,
  CANCEL: 3,
  REQUEST_STATUS: 4
});

export const CharacterizationActionFlag = Object.freeze({
  DISCARD: 0,
  SAVE: 1,
  APPLY_ACCELERATION: 2,
  APPLY_JERK: 4
});

export const ParameterId = Object.freeze({
  BAUD: 1,
  CONTROL_PERIOD_US: 2,
  COUNTS_PER_REVOLUTION: 3,
  STREAM_RATE_HZ: 4,
  KP: 5,
  KI: 6,
  KD: 7,
  MAXIMUM_VELOCITY: 8,
  MAXIMUM_ACCELERATION: 9,
  MAXIMUM_JERK: 10,
  MAXIMUM_CURRENT: 11,
  MAXIMUM_DUTY: 12,
  FORWARD_DEADBAND: 13,
  REVERSE_DEADBAND: 14,
  MOTOR_DIRECTION: 15,
  SUPPLY_DIVIDER_GAIN: 16,
  SUPPLY_INPUT_OFFSET: 17,
  MINIMUM_SUPPLY_VOLTAGE: 18,
  MAXIMUM_SUPPLY_VOLTAGE: 19,
  CURRENT_GAIN: 20,
  CURRENT_OFFSET: 21,
  ENCODER_TIMEOUT_MS: 22,
  ENCODER_TIMEOUT_VELOCITY: 23,
  MAXIMUM_FEEDBACK_CORRECTION: 24,
  ESTIMATOR_MINIMUM_COUNTS: 25,
  ESTIMATOR_MAXIMUM_WINDOW_US: 26,
  ESTIMATOR_STALE_TIMEOUT_US: 27,
  CURRENT_SENSE_ENABLED: 28,
  CURRENT_FILTER_CUTOFF_HZ: 29,
  ZERO_INDEX_MINIMUM_INTERVAL_US: 30,
  ZERO_INDEX_CORRECTION_GAIN: 31,
  ZERO_INDEX_MINIMUM_SEPARATION_REVOLUTIONS: 32,
  CHARACTERIZATION_DYNAMICS_FILTER_CUTOFF_HZ: 33,
  CHARACTERIZATION_DYNAMICS_QUANTILE: 34,
  CHARACTERIZATION_RECOMMENDATION_SAFETY_FACTOR: 35,
  VELOCITY_ESTIMATOR_METHOD: 36,
  VELOCITY_ACCELERATION_WINDOW_SAMPLES: 37,
  ROTOR_ZERO_OFFSET_TICKS: 38,
  ZERO_INDEX_REFERENCE_SIDE: 39,
  ZERO_INDEX_CALIBRATION_DUTY: 40,
  ZERO_INDEX_CALIBRATION_TIMEOUT_MS: 41,
  ZERO_INDEX_CALIBRATION_REVERSAL_PAUSE_MS: 42,
  ZERO_INDEX_CALIBRATION_MAXIMUM_ERROR_TICKS: 43,
  ZERO_INDEX_CALIBRATION_SPEED_RPM: 44,
  JERK_LIMIT_ENABLED: 45
});
